### ISSUE TITLE
New CWL log groups should be ingested automatically

### ISSUE THREAD

**Issue by mweiden** [HumanCellAtlas/logs#2]
Connects to https://github.com/HumanCellAtlas/data-store/issues/532

## User story
As an HCA developer,
I want all new CWL log groups to be ingested into the ELK stack automagically,
so that no manual configuration needs to be done and logs for all applications in production are indexed.

## Context
When a new log group is created, a subscription filter needs to be created for the CWL to ELK exporter for logs to be exported from that log group into ELK. Currently, this is accomplished with `subscribe.sh`, but it should be done on log group creation.

The creation of the subscription filter could be automated by consuming the log group creation event from SQS.

**Comment by parthshahva** [comment]
https://github.com/HumanCellAtlas/logs/pull/17
