### ISSUE TITLE
Production firehose subscriber and its integration test compete to subscribe log group

### ISSUE THREAD

**Issue by mweiden** [HumanCellAtlas/logs#35]
The firehose subscriber creates a log group in order to test the behavior of assigning it a subscription filter to send logs from that log group to firehose. The issue with this is that creating the log group also notifies an existing subscriber deployed in production. One of two bad outcomes will result

1. The test will pass, but the production lambda will fail since a filter with that name is already created.
2. The production lambda will subscribe the log group before the test does and the test will fail

**Comment by parthshahva** [comment]
https://github.com/HumanCellAtlas/logs/pull/39
