### ISSUE TITLE
The CWL to ELK exporter runs too often

### ISSUE THREAD

**Issue by mweiden** [HumanCellAtlas/logs#4]
The CloudWatch Logs lambda filter pushes logs to the `cwl_to_elk` exporter in too fine a granularity, causing the function to run too often.

To fix this problem we may have to move the exporter to work from a Kinesis stream so that the messages can be pulled in batch.

**Comment by parthshahva** [comment]
completed in https://github.com/HumanCellAtlas/logs/pull/11
