### ISSUE TITLE
Support EBI in migrating onto centralized logging system

### ISSUE THREAD

**Issue by mweiden** [HumanCellAtlas/logs#48]
## Need (user story)
* As an operator of the ingest system or an operator of the DCP more generally
* I want an automated/reproducable deployment of the integration between the ingest system and the logging system
* so that I can view ingest logs.

**Comment by kozbo** [comment]
Should this be included in the Pilot Phase release?

**Comment by mweiden** [comment]
@kozbo yes, optimally

**Comment by parthshahva** [comment]
Apologies for the delay. This is done. Log groups can be found at https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logs:prefix=/aws/eks. Pod names are used as log stream names

**Comment by parthshahva** [comment]
Deploying small fix. Format of cloudwatch log group will now be /aws/eks/ingest/#{namespace_label}/#{application_name}
