### ISSUE TITLE
Kibana in `dev` returns duplicate hits for a single log record

### ISSUE THREAD

**Issue by hannes-ucsc** [HumanCellAtlas/logs#56]
One log record: 

<img width="1501" alt="screen shot 2018-09-26 at 8 45 11 pm" src="https://user-images.githubusercontent.com/5143256/46122394-467f3b80-c1cd-11e8-851e-55874d8088cd.png">

Nine hits:

<img width="1503" alt="screen shot 2018-09-26 at 8 48 22 pm" src="https://user-images.githubusercontent.com/5143256/46122455-9231e500-c1cd-11e8-8d10-cdd63b719f81.png">

**Comment by mweiden** [comment]
@hannes-ucsc are you still seeing this behavior? I can't seem to replicate this.

**Comment by hannes-ucsc** [comment]
Yes, occasionally. How did you attempt to reproduce it?

**Comment by mweiden** [comment]
@hannes-ucsc I dug through some log lines similar to the ones you showed and tried to find duplicates

**Comment by mweiden** [comment]
I think this may have something to do with an OOM issue we're seeing in the dev deployment...

OOM report
```
REPORT RequestId: 04f76c37-fca4-11e8-a7ec-e52492b51ce1	Duration: 5983.41 ms	Billed Duration: 6000 ms Memory Size: 1024 MB	Max Memory Used: 1024 MB	
```

This is retried
```
RequestId: 04f76c37-fca4-11e8-a7ec-e52492b51ce1 Process exited before completing request
RequestId: 04f76c37-fca4-11e8-a7ec-e52492b51ce1 Process exited before completing request
RequestId: 04f76c37-fca4-11e8-a7ec-e52492b51ce1 Process exited before completing request
```
