### ISSUE TITLE
Operator Documentation (RunBooks)

### ISSUE THREAD

**Issue by sampierson** [HumanCellAtlas/logs#69]
Internal.

Runbook should detail how to deploy the component.
Runbook should detail how to roll-back a deployment.
Runbook should provide guidance on how to diagnose / resolve common problems.

Create your RunBook on allspark.dev.data.humancellatlas.org
Put a link to it in this page: https://allspark.dev.data.humancellatlas.org/dcp-ops/docs/wikis/home

Examples:

https://github.com/HumanCellAtlas/ingest-central/blob/master/release-manager-playbook.md

[SOP: Releasing new Versions of DCP Software](https://docs.google.com/document/d/1HbSWuIABaavaHpCwaO0peA_uwTW5wBCdRnYoz7ZVQuQ/edit?ts=5b0d7550#heading=h.yw6cvy5vlmbu)

[Playbook template in doc form](https://docs.google.com/document/d/1EPcN1tEIwMuzRXj8JPARd-Vgnc3sXJvwQOEcVWkVaYc/edit)

**Comment by stahiri** [comment]
This work has shifted to Q4 as carryover MUST HAVE work. Release and milestone have been updated due to this. This needs to be assigned an owner.

**Comment by stahiri** [comment]
@sampierson I actually don't think this is relevant to this repo - do you agree?

**Comment by sampierson** [comment]
Actually, the logging infrastructure is not trivial, and does require being deployed.  We need to know how to deploy it, if Matt gets hit by a bus, so yes, I think it does apply to this repo.

**Comment by stahiri** [comment]
Thanks @sampierson --- very helpful. 

@mweiden, given Sam's note above that we'd be in trouble if you got hit by a bus, are you the person who has to draft this runbook or is there someone else we can assign to this?

**Comment by mweiden** [comment]
@stahiri I'm the right person. Assigning it to myself and putting it on my TODO list.

**Comment by stahiri** [comment]
Hi @mweiden - any update on the runbook for this? The rest of the runbooks are complete (woohoo!)

**Comment by mweiden** [comment]
@stahiri complete!
