### ISSUE TITLE
Internal Server Errors

### ISSUE THREAD

**Issue by amarjandu** [HumanCellAtlas/logs#81]
Hey when accessing https://logs.dev.data.humancellatlas.org/_plugin/kibana, i get an internal server error. 
![Screen Shot 2019-05-29 at 8 51 43 AM](https://user-images.githubusercontent.com/1947534/58571692-1fab5600-81ef-11e9-9410-6803fc672fe3.png)

**Comment by mweiden** [comment]
This should be fixed now.

Note that the elk-oidc-proxy can only keep a token open for you for an hour. You may need to refresh the page occasionally.
